### ISSUE TITLE
why the REST API plugin dosn't  work?

### ISSUE THREAD

**Issue by jerseycolipot** [igniterealtime/openfire-restAPI-plugin#186]
I have been using Openfire server 4.6.2, and the REST API plugin was version 1.5.0. I made some code modifications by adding an interface for the server to send messages to users. The main changes include modifying the Message.Service with the addition of "Code 1". The relevant class is SendMsgComponet, where the "Code 2" segment is involved. Due to a vulnerability, I decided to upgrade Openfire to version 4.7.5. However, after upgrading Openfire and uploading the plugin, it seems not to be working, and the error message is as follows. How can I fix this?
code 1
```
@POST
@Path("/send")
@Produces({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
public String sendMessage(MessageEntityToSomeBody messageEntityToSomeBody) {

    Message msg = new Message();


    Logger Log = LoggerFactory.getLogger(MessageService.class);
    Log.debug("body:" + messageEntityToSomeBody.getBody() + " fromJid:" + messageEntityToSomeBody.getFromJid() + " toJid:" + messageEntityToSomeBody.getToJid());

    msg.setBody(messageEntityToSomeBody.getBody());
    msg.setFrom(messageEntityToSomeBody.getFromJid());//发信人
    msg.setTo(messageEntityToSomeBody.getToJid());//接收人
    msg.setType(Message.Type.chat);//为聊天信息
    msg.setSubject(messageEntityToSomeBody.getSubject());
    if (messageEntityToSomeBody.getMsgBodyType() != null && !messageEntityToSomeBody.getMsgBodyType().isEmpty()) {
        msg.addChildElement("msgBodyType","").setText(messageEntityToSomeBody.getMsgBodyType());
    }
    SendMsgComponet sendMsgComponet = new SendMsgComponet();
    sendMsgComponet.SendMsg(msg);

    return "";
}
```

code 2
```
package org.jivesoftware.openfire.plugin.rest.service;

import org.xmpp.component.Component;
import org.xmpp.component.ComponentException;
import org.xmpp.component.ComponentManager;
import org.xmpp.component.ComponentManagerFactory;
import org.xmpp.packet.JID;
import org.xmpp.packet.Message;
import org.xmpp.packet.Packet;

public class SendMsgComponet implements Component {


    private static final String COMPONENTNAME = "sendservlet";//组件名
    private ComponentManager componentManager;//组件管理

    public SendMsgComponet()
    {
        componentManager = ComponentManagerFactory.getComponentManager();
        try {
            componentManager.addComponent(COMPONENTNAME, this);
        } catch (Exception err) {
            err.printStackTrace();
        }
    }

    ///发送消息
    public  void SendMsg(Message message)
    {
        try {
            componentManager.sendPacket(this, message);//发关
        } catch (ComponentException e) {
            e.printStackTrace();
        }
    }

    ///发送消息
//    public  void SendMsgNew(MessageSendEntity messageSendEntity)
//    {
//        try {
//            componentManager.sendPacket(this, messageSendEntity);//发关
//        } catch (ComponentException e) {
//            e.printStackTrace();
//        }
//    }

    @Override
    public String getName() {
        return  COMPONENTNAME;
    }

    @Override
    public String getDescription() {
        return null;
    }

    @Override
    public void processPacket(Packet packet) {

    }

    @Override
    public void initialize(JID jid, ComponentManager componentManager) throws ComponentException {

    }

    @Override
    public void start() {

    }

    @Override
    public void shutdown() {

    }
}
```
the exception
```
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar:3.1.0]
    at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1459) ~[jetty-servlet-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[jetty-servlet-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626) ~[jetty-servlet-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.jivesoftware.admin.PluginFilter.doFilter(PluginFilter.java:226) ~[xmppserver-4.7.5.jar:4.7.5]
    at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.jivesoftware.admin.AuthCheckFilter.doFilter(AuthCheckFilter.java:254) ~[xmppserver-4.7.5.jar:4.7.5]
    at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.43.v20210629.jar:9.4.43.v20210629]
    at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129) ~[sitemesh-2.4.2.jar:?]
    at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77) ~[sitemesh-2.4.2.jar:?]
    at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201) ~[jetty-servlet-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548) ~[jetty-servlet-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602) ~[jetty-security-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434) ~[jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) ~[jetty-servlet-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349) ~[jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191) ~[jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146) ~[jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388) ~[jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633) [jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380) [jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) [jetty-server-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) [jetty-util-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) [jetty-util-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) [jetty-util-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [jetty-util-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386) [jetty-util-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) [jetty-util-9.4.43.v20210629.jar:9.4.43.v20210629]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) [jetty-util-9.4.43.v20210629.jar:9.4.43.v20210629]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]
```

**Comment by jerseycolipot** [comment]
please help 。 My server hacked by hacker and lock much files ，but the first work is recover chat service!

**Comment by guusdk** [comment]
This issue tracker is intended for reporting bugs. If you seek help, please ask your questions in the forum of the Ignite Realtime community. You can find this community at https://discourse.igniterealtime.org

The version of the REST API plugjn that you mention is old. It is recommended to use the latest release.

The stack trace that you're providing misses the first line (which contains the error message).

Make sure that you have performed this step of the installation of the REST API plugin:
> _Important Step:_ To enable the plugin make sure to set the system property `adminConsole.access.allow-wildcards-in-excludes` to `true`

**Comment by jerseycolipot** [comment]
> This issue tracker is intended for reporting bugs. If you seek help, please ask your questions in the forum of the Ignite Realtime community. You can find this community at https://discourse.igniterealtime.org
> 
> The version of the REST API plugjn that you mention is old. It is recommended to use the latest release.
> 
> The stack trace that you're providing misses the first line (which contains the error message).
> 
> Make sure that you have performed this step of the installation of the REST API plugin:
> 
> > _Important Step:_ To enable the plugin make sure to set the system property `adminConsole.access.allow-wildcards-in-excludes` to `true`

thank you for answer，I have change  `adminConsole.access.allow-wildcards-in-excludes` to `true` ,but it dosn't work !
I find that I download code souce of the rest plugin 1.10.2  from githut and I change nothing ,I juse package it by maven and then I get a jar named 'restAPI-openfire-plugin-assembly.jar' ,then  I upload it to plugin center , when I vist rest api  ,it throw a expection ,here  is the fullinfo
`异常：
java.lang.NullPointerException

	at org.jivesoftware.openfire.plugin.restAPI.rest_002dapi_jsp._jspService(rest_002dapi_jsp.java:203)

	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

	at org.jivesoftware.openfire.container.PluginServlet.handleJSP(PluginServlet.java:462)

	at org.jivesoftware.openfire.container.PluginServlet.service(PluginServlet.java:122)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1459)

	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)

	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)

	at org.jivesoftware.admin.PluginFilter.doFilter(PluginFilter.java:226)

	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)

	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)

	at org.jivesoftware.admin.AuthCheckFilter.doFilter(AuthCheckFilter.java:254)

	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)

	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)

	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)

	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)

	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)

	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)

	at org.jivesoftware.util.LocaleFilter.doFilter(LocaleFilter.java:73)

	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)

	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)

	at org.jivesoftware.util.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:49)

	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)

	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)

	at org.jivesoftware.admin.PluginFilter.doFilter(PluginFilter.java:226)

	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)

	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)

	at org.jivesoftware.admin.AuthCheckFilter.doFilter(AuthCheckFilter.java:254)

	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201)

	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)

	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)

	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)

	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)

	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)

	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)

	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)

	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)

	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)

	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)

	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)

	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)

	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)

	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)

	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)

	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191)

	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)

	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)

	at org.eclipse.jetty.server.Server.handle(Server.java:516)

	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)

	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)

	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)

	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)

	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)

	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)

	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)

	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)

	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)

	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)

	at java.lang.Thread.run(Thread.java:748)
`
