### ISSUE TITLE
Why can't I manually package the source code of the REST API plugin? 

### ISSUE THREAD

**Issue by jerseycolipot** [igniterealtime/openfire-restAPI-plugin#187]
My Openfire version is 4.7.5, and I downloaded the source code of the REST API plugin from GitHub (version 1.10.2). I opened the source code with IntelliJ IDEA, used Maven for packaging, and obtained a JAR file named 'restAPI-openfire-plugin-assembly.jar.' After uploading this JAR file in the Openfire console's Plugin tab, when I try to access 'Server -> Server Settings -> REST API,' an error occurs. However, if I install the REST API plugin online through the Plugin Center, everything works fine. Why is this happening? Below is the error message
`

异常：
java.lang.NullPointerException

	at org.jivesoftware.openfire.plugin.restAPI.rest_002dapi_jsp._jspService(rest_002dapi_jsp.java:203)

	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

	at org.jivesoftware.openfire.container.PluginServlet.handleJSP(PluginServlet.java:462)

	at org.jivesoftware.openfire.container.PluginServlet.service(PluginServlet.java:122)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1459)

	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)

	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)

	at org.jivesoftware.admin.PluginFilter.doFilter(PluginFilter.java:226)

	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)

	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)

	at org.jivesoftware.admin.AuthCheckFilter.doFilter(AuthCheckFilter.java:254)

	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)

	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)

	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)

	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)

	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)

	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)

	at org.jivesoftware.util.LocaleFilter.doFilter(LocaleFilter.java:73)

	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)

	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)

	at org.jivesoftware.util.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:49)

	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)

	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)

	at org.jivesoftware.admin.PluginFilter.doFilter(PluginFilter.java:226)

	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)

	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)

	at org.jivesoftware.admin.AuthCheckFilter.doFilter(AuthCheckFilter.java:254)

	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201)

	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)

	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)

	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)

	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)

	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)

	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)

	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)

	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)

	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)

	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)

	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)

	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)

	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)

	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)

	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)

	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191)

	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)

	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)

	at org.eclipse.jetty.server.Server.handle(Server.java:516)

	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)

	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)

	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)

	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)

	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)

	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)

	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)

	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)

	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)

	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)

	at java.lang.Thread.run(Thread.java:748)
`

**Comment by guusdk** [comment]
As I have explained to you before, this issue tracker is intended for reporting bugs. If you seek help, please ask your questions in the forum of the Ignite Realtime community. You can find this community at https://discourse.igniterealtime.org
