### ISSUE TITLE
Readiness and liveness probes broken since openfire 4.8.0

### ISSUE THREAD

**Issue by pdefreitas** [igniterealtime/openfire-restAPI-plugin#190]
We're currently using readiness and liveness probes and they seem to be broken since openfire 4.8.0 has been launched.

It seems this line of code is throwing an exception:
https://github.com/igniterealtime/openfire-restAPI-plugin/blame/main/src/java/org/jivesoftware/openfire/plugin/rest/controller/SystemController.java#L257

Since Apache MINA was replaced by Netty this method no longer exists:
https://github.com/igniterealtime/Openfire/blob/v4.8.1/xmppserver/src/main/java/org/jivesoftware/openfire/spi/ConnectionListener.java

**Logs:**
```
2024.03.11 16:58:22.973 ERROR [Jetty-QTP-AdminConsole-XX]: org.jivesoftware.openfire.container.PluginServlet - org.glassfish.jersey.server.ContainerException: java.lang.NoSuchMethodError: 'org.apache.mina.transport.socket.nio.NioSocketAcceptor org.jivesoftware.openfire.spi.ConnectionListener.getSocketAcceptor()'
javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.NoSuchMethodError: 'org.apache.mina.transport.socket.nio.NioSocketAcceptor org.jivesoftware.openfire.spi.ConnectionListener.getSocketAcceptor()'
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:410) ~[?:?]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) ~[?:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358) ~[?:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311) ~[?:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) ~[?:?]
	at org.jivesoftware.openfire.container.PluginServlet.handleServlet(PluginServlet.java:468) ~[xmppserver-4.8.1.jar:4.8.1]
...
```

**Comment by pdefreitas** [comment]
I guess fixing this bug depends on https://igniterealtime.atlassian.net/browse/OF-2789

**Comment by guusdk** [comment]
Fixed by https://github.com/igniterealtime/openfire-restAPI-plugin/pull/194
