### ISSUE TITLE
500 Error for API requests

### ISSUE THREAD

**Issue by garyhill01** [igniterealtime/openfire-restAPI-plugin#36]
Hi 

Whatever request I make using the API I get a 500 error.

Simple GET list of users request : https://myurl:9090/plugins/restapi/v1/users

Openfire v.4.5.0
API v.1.3.9

Anyone else had this issue/pointers where to look?

Thanks
Gary

**Comment by Redor** [comment]
Could you please try with the REST API Plugin 1.3.10 Version: https://github.com/igniterealtime/openfire-restAPI-plugin/releases/tag/1.3.10

**Comment by garyhill01** [comment]
Thanks for the prompt response, exactly the same issue.

If this is any help it's from stderror.log 👍 
javax.ws.rs.WebApplicationException: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
        at com.sun.jersey.core.provider.jaxb.AbstractRootElementProvider.writeTo(AbstractRootElementProvider.java:159)
        at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

Snipped here ......

**Comment by Redor** [comment]
Do you send the Header "Content-Type"?
Header: Content-Type: application/xml

Or do you tried the JSON format? by setting the "Accept" header
Accept: application/json

**Comment by garyhill01** [comment]
Thank you - it needed Accept: application/json to make it work.

Cheers
Gary
