### ISSUE TITLE
Please upgrade jackson libs to latest

### ISSUE THREAD

**Issue by danieltet** [igniterealtime/openfire-restAPI-plugin#37]
Once I went live with version 4.5.1 of Openfire and Version 1.3.9 of openfire-RestAPI plugin I started getting this error:

Exception in thread "socket_c2s-thread-13" java.lang.NoSuchMethodError: org.codehaus.jackson.type.JavaType.isMapLikeType()Z
	at org.codehaus.jackson.map.ser.BasicSerializerFactory.buildContainerSerializer(BasicSerializerFactory.java:416)
	at org.codehaus.jackson.map.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:268)
	at org.codehaus.jackson.map.ser.StdSerializerProvider._createUntypedSerializer(StdSerializerProvider.java:782)
	at org.codehaus.jackson.map.ser.StdSerializerProvider._createAndCacheUntypedSerializer(StdSerializerProvider.java:735)
	at org.codehaus.jackson.map.ser.StdSerializerProvider.findValueSerializer(StdSerializerProvider.java:344)
	at org.codehaus.jackson.map.ser.StdSerializerProvider.findTypedValueSerializer(StdSerializerProvider.java:420)
	at org.codehaus.jackson.map.ser.StdSerializerProvider._serializeValue(StdSerializerProvider.java:601)
	at org.codehaus.jackson.map.ser.StdSerializerProvider.serializeValue(StdSerializerProvider.java:256)
	at org.codehaus.jackson.map.ObjectMapper._configAndWriteValue(ObjectMapper.java:2575)
	at org.codehaus.jackson.map.ObjectMapper.writeValueAsString(ObjectMapper.java:2097)
	at com.notnoop.apns.PayloadBuilder.build(PayloadBuilder.java:365)
	at com.vclik.VClikPlugin.push_message(....)
	at com.vclik.VClikPlugin$1.processIncoming(....)

After doing some research I found that this may be related to conflicting versions of jackson libraries. See here:
https://stackoverflow.com/questions/11784051/nosuchmethoderror-org-codehaus-jackson-type-javatype 

So I looked at all the jackson libs in my openfire install:

[..... openfire_4_5_1]$ find . -name "*jackson*"
./plugins/restapi/lib/jackson-core-asl-1.9.2.jar
./plugins/restapi/lib/jackson-mapper-asl-1.9.2.jar
./plugins/restapi/lib/jackson-jaxrs-1.9.2.jar
./plugins/restapi/lib/jackson-xc-1.9.2.jar
./plugins/userstatus/lib/jackson-xc-1.9.11.jar
./plugins/userstatus/lib/jackson-mapper-asl-1.9.11.jar
./plugins/userstatus/lib/jackson-jaxrs-1.9.11.jar
./plugins/userstatus/lib/jackson-core-asl-1.9.11.jar
./plugins/monitoring/lib/jackson-core-asl-1.9.11.jar
./plugins/monitoring/lib/jackson-jaxrs-1.9.11.jar
./plugins/monitoring/lib/jackson-xc-1.9.11.jar
./plugins/monitoring/lib/jackson-mapper-asl-1.9.11.jar
./plugins/getallexternalfriends/lib/jackson-mapper-asl-1.9.11.jar
./plugins/getallexternalfriends/lib/jackson-all-1.7.4.jar
./plugins/getallexternalfriends/lib/jackson-xc-1.9.11.jar
./plugins/getallexternalfriends/lib/jackson-core-asl-1.9.11.jar
./plugins/getallexternalfriends/lib/jackson-jaxrs-1.9.11.jar

Notice how all the other plugins have version 1.9.11 and restAPI has version 1.9.2 of all the jackson libs. It should also be notedt hat the monitoring, userstatus and getexternalfriends complied from source while restAPI I thought I'd just use off the shelf - and it came with older jackson libs.

I did not notice this problem in dev, perhaps because of low load/not too many threads. I will continue testing some more, and will compile restAPI from scratch as well to see if that fixes my problem.

Please consider upgrading to the latest jackson libs in prod version of restAPI to avoid this problem.

**Comment by wrooot** [comment]
Is it the same with 1.3.10 version? http://www.igniterealtime.org/projects/openfire/plugin-archive.jsp?plugin=restAPI

**Comment by danieltet** [comment]
Yes I noticed that 1.3.9 and 1.3.10 have the same (older) version of jackson libraries. Should not the package off the shelf have the latest libs? or should I downgrade. Also compare with userstatus and others who seem to have the latest.

**Comment by Redor** [comment]
Check out the latest release (1.4.0) which provides the same jackson
https://igniterealtime.org/projects/openfire/plugins.jsp
